<?php

// autoload.php @generated by Composer

// require_once __DIR__ . '/composer' . '/autoload_real.php';
require_once __DIR__ . '/jpush/jpush/vendor/composer' . '/autoload_real.php';

return ComposerAutoloaderInit060ff8550ffe9f5e6136a140c07c1abc::getLoader();
